<div id="sidr">
<ul>
<li><a href="?c=01">金融-金融総合</a></li>
<li><a href="?c=02">金融-地方銀行</a></li>
<li><a href="?c=03">金融-信用金庫</a></li>
<li><a href="?c=04">金融-政府系金融機関</a></li>
<li><a href="?c=05">金融-証券取引所</a></li>
<li><a href="?c=06">金融-保険</a></li>
<li><a href="?c=07">金融-ベンチャーキャピタル</a></li>
<li><a href="?c=08">金融-信連(JAバンク)</a></li>
<li><a href="?c=09">金融-リース</a></li>
<li><a href="?c=10">金融-証券</a></li>
<li><a href="?c=11">金融-クレジットカード</a></li>
<li><a href="?c=12">マスコミ-マスコミ</a></li>
<li><a href="?c=13">マスコミ-広告</a></li>
<li><a href="?c=14">マスコミ-出版</a></li>
<li><a href="?c=15">マスコミ-教科書出版</a></li>
<li><a href="?c=16">マスコミ-アニメ</a></li>
<li><a href="?c=17">製造-メーカー総合</a></li>
<li><a href="?c=18">製造-自動車</a></li>
<li><a href="?c=19">製造-化学</a></li>
<li><a href="?c=20">製造-半導体・電子部品</a></li>
<li><a href="?c=21">製造-重工業・造船</a></li>
<li><a href="?c=22">製造-電機</a></li>
<li><a href="?c=23">製造-印刷・製紙</a></li>
<li><a href="?c=24">製造-素材メーカー</a></li>
<li><a href="?c=25">製造-工作機械</a></li>
<li><a href="?c=26">製造-建機・農機</a></li>
<li><a href="?c=27">製造-鉄鋼</a></li>
<li><a href="?c=28">製造-非鉄金属</a></li>
<li><a href="?c=29">製造-精密機器</a></li>
<li><a href="?c=30">製造-製薬(R&D)</a></li>
<li><a href="?c=31">製造-製薬(MR)</a></li>
<li><a href="?c=32">製造-医療機器</a></li>
<li><a href="?c=33">製造-化粧品</a></li>
<li><a href="?c=34">製造-文具・筆記具</a></li>
<li><a href="?c=35">製造-プラント・エンジニア</a></li>
<li><a href="?c=36">製造-食品</a></li>
<li><a href="?c=37">製造-おもちゃ</a></li>
<li><a href="?c=38">製造-お菓子</a></li>
<li><a href="?c=39">情報通信-IT総合</a></li>
<li><a href="?c=40">情報通信-ネットワーク</a></li>
<li><a href="?c=41">情報通信-家庭用ゲーム</a></li>
<li><a href="?c=42">情報通信-メーカー系子会社</a></li>
<li><a href="?c=43">情報通信-WEBサービス</a></li>
<li><a href="?c=44">情報通信-通信キャリア</a></li>
<li><a href="?c=45">情報通信-ユーザー系子会社</a></li>
<li><a href="?c=46">流通-商社</a></li>
<li><a href="?c=47">流通-専門商社</a></li>
<li><a href="?c=48">流通-石油</a></li>
<li><a href="?c=49">流通-物流</a></li>
<li><a href="?c=50">流通-外食</a></li>
<li><a href="?c=51">流通-アパレル</a></li>
<li><a href="?c=52">流通-小売</a></li>
<li><a href="?c=53">建設・不動産-建設</a></li>
<li><a href="?c=54">建設・不動産-メーカー(営業)</a></li>
<li><a href="?c=55">建設・不動産-メーカー(技術)</a></li>
<li><a href="?c=56">建設・不動産-通信建設</a></li>
<li><a href="?c=57">建設・不動産-道路</a></li>
<li><a href="?c=58">建設・不動産-ビルメンテ・管理</a></li>
<li><a href="?c=59">建設・不動産-不動産</a></li>
<li><a href="?c=60">建設・不動産-不動産流通</a></li>
<li><a href="?c=61">公共福祉-公務員</a></li>
<li><a href="?c=62">公共福祉-国I</a></li>
<li><a href="?c=63">公共福祉-非営利団体</a></li>
<li><a href="?c=64">公共福祉-教員・教職</a></li>
<li><a href="?c=65">公共福祉-インフラ </a></li>
<li><a href="?c=66">公共福祉-鉄道</a></li>
<li><a href="?c=67">公共福祉-ガス</a></li>
<li><a href="?c=68">その他-研究所</a></li>
<li><a href="?c=69">その他-ホテル</a></li>
<li><a href="?c=70">その他-コンサルティング</a></li>
<li><a href="?c=71">その他-人材</a></li>
<li><a href="?c=72">その他-農林水産</a></li>
<li><a href="?c=73">その他-アミューズメント</a></li>
<li><a href="?c=74">その他-競馬関連企業</a></li>
<li><a href="?c=75">その他-学習塾・予備校</a></li>
<li><a href="?c=76">その他-音楽</a></li>
<li><a href="?c=77">その他-マーケ・リサーチ</a></li>
</ul>
</div>
