<h2>製造業 - 素材メーカー</h2>
<section><!-- Case1 -->
<hr/>
<div class="row-fluid mt20 mb10">


<h3 class="rank1"> Sランク 偏差値70～ </h3>
<div class="company"><span class="no-company">該当企業ありません</span></div>
<h3 class="rank2"> Aランク 偏差値65～69 </h3>
<div class="company">新日鐵</div>
<h3 class="rank3"> Bランク 偏差値60～64 </h3>
<div class="company">JFE</div>
<div class="company">旭硝子</div>
<div class="company">住友金属</div>
<div class="company">住友電工</div>
<div class="company">住友化学</div>
<div class="company">三菱化学</div>
<div class="company">信越化学</div>
<div class="company">神戸製鋼</div>
<div class="company">三菱マテリアル</div>
<div class="company">旭化成</div>
<div class="company">東レ</div>
<div class="company">住友鉱山</div>
<div class="company">JX金属</div>
<div class="company">三井化学</div>
<div class="company">昭和電工</div>
<div class="company">帝人</div>
<div class="company">JSR</div>
<div class="company">王子製紙</div>
<div class="company">古河電工</div>
<div class="company">日新製鋼</div>
<div class="company">大陽日酸</div>
<div class="company">宇部興産</div>
<div class="company">日東電工</div>
<div class="company">積水化学</div>
<div class="company">太平洋セメント</div>
<div class="company">日本製紙</div>
<div class="company">クラレ</div>
<h3 class="rank4"> Cランク 偏差値55～59 </h3>
<div class="company">日立金属</div>
<div class="company">三井金属</div>
<div class="company">フジクラ</div>
<div class="company">三菱瓦斯化学</div>
<div class="company">東ソー</div>
<div class="company">カネカ</div>
<div class="company">日立化成</div>
<div class="company">住友ベークライト</div>
<div class="company">日本板硝子</div>
<div class="company">大同特殊鋼</div>
<div class="company">DOWA</div>
<div class="company">日本軽金属</div>
<div class="company">日立電線</div>
<div class="company">トクヤマ</div>
<div class="company">日本電気硝子</div>
<div class="company">三菱レイヨン</div>
<div class="company">日本触媒</div>
<div class="company">日本ゼオン</div>
<div class="company">日産化学</div>
<div class="company">関西ペイント</div>
<div class="company">日本ペイント</div>
<div class="company">高砂香料</div>
<div class="company">長谷川香料</div>
<div class="company">東京製鐵</div>
<div class="company">JFE鋼板</div>
<div class="company">愛知製鋼</div>
<div class="company">古河機械金属</div>
<div class="company">ADEKA</div>
<div class="company">エア・ウォーター</div>
<div class="company">電機化学</div>
<div class="company">東京応化</div>
<div class="company">日本エア・リキード</div>
<div class="company">日本高純度化学</div>
<div class="company">ダイセル化学</div>
<div class="company">三洋特殊鋼</div>
<div class="company">古河スカイ</div>
<div class="company">積水化成品</div>
<div class="company">セントラル硝子</div>
<div class="company">三菱樹脂</div>
<div class="company">日本曹達</div>
<div class="company">東洋インキ</div>
<div class="company">住友大阪セメント</div>
<div class="company">レンゴー</div>
<div class="company">三菱製紙</div>
<div class="company">住友軽金属</div>
<div class="company">クレハ</div>
<div class="company">大日精化</div>
<div class="company">日本化薬</div>
<div class="company">日本パーカラジインク</div>
<div class="company">東洋紡</div>
<div class="company">日清紡</div>
<div class="company">北越製紙</div>
<h3 class="rank5"> Dランク 偏差値50～54 </h3>
<div class="company">東邦亜鉛</div>
<div class="company">昭和電線</div>
<div class="company">三菱電線</div>
<div class="company">日油</div>
<div class="company">コニシ</div>
<div class="company">サカタインクス</div>
<div class="company">三洋化成</div>
<div class="company">新日鐵化学</div>
<div class="company">窒素</div>
<div class="company">東亞合成</div>
<div class="company">三菱アルミニウム</div>
<div class="company">哀歌</div>
<div class="company">石原産業</div>
<div class="company">堺化学</div>
<div class="company">JSP</div>
<div class="company">住友精化</div>
<div class="company">保土谷化学</div>
<div class="company">本州化学</div>
<div class="company">大王製紙</div>
<div class="company">東邦チタニウム</div>
<div class="company">荒川化学</div>
<div class="company">関東電化</div>
<div class="company">四国化成</div>
<div class="company">昭和高分子</div>
<div class="company">積水樹脂</div>
<div class="company">ダイソー</div>
<div class="company">中越パルプ</div>
<div class="company">タツタ電線</div>
<div class="company">テイカ</div>
<div class="company">日本合成化学</div>
<div class="company">ハリマ化成</div>
<div class="company">藤倉化成</div>
<div class="company">日本精化</div>
<div class="company">日本農薬</div>
<div class="company">ユニチカ</div>
<div class="company">エスケー化研</div>
<div class="company">第一工業製薬</div>
<div class="company">大日本塗料</div>
<div class="company">日本カーリット</div>
<div class="company">北興化学</div>
<h3 class="rank6"> Eランク 偏差値45～49 </h3>
<div class="company">富山化学</div>
<div class="company">日東紡</div>
<div class="company">日本化学</div>
<div class="company">日本化成</div>
<div class="company">ﾗｻ工業</div>
<div class="company">大倉工業</div>
<div class="company">ｺｰﾌﾟｹﾐｶﾙ</div>
<div class="company">東洋合成</div>
<div class="company">有機合成薬品</div>
<div class="company">ｸﾗﾎﾞｳ</div>
<div class="company">日本ｶｰﾊﾞｲﾄﾞ</div>
<h3 class="rank7"> Fランク 偏差値40～44 </h3>
<div class="company"><span class="no-company">該当企業ありません</span></div>

</div>
</section><!-- /Case1 -->

