<h2>製造業 - 自動車</h2>
<section><!-- Case1 -->
<hr/>
<div class="row-fluid mt20 mb10">


<h3 class="rank1"> Sランク 偏差値70～ </h3>
<div class="company">トヨタ自動車</div>
<div class="company">本田技研工業</div>
<h3 class="rank2"> Aランク 偏差値65～69 </h3>
<div class="company">デンソー</div>
<div class="company">日産自動車</div>
<h3 class="rank3"> Bランク 偏差値60～64 </h3>
<div class="company">豊田自動織機</div>
<div class="company">マツダ</div>
<div class="company">スズキ　</div>
<div class="company">ヤマハ発動機</div>
<div class="company">いすゞ自動車</div>
<div class="company">トヨタ車体</div>
<div class="company">ダイハツ</div>
<div class="company">アイシン精機　</div>
<div class="company">三菱自動車</div>
<div class="company">ブリヂストン</div>
<h3 class="rank4"> Cランク 偏差値55～59 </h3>
<div class="company">アイシンAW</div>
<div class="company">日野自動車</div>
<div class="company">関東自動車</div>
<div class="company">日本ガイシ</div>
<div class="company">富士重工業</div>
<div class="company">ボッシュ</div>
<div class="company">トヨタ紡織</div>
<div class="company">ジェイテクト</div>
<div class="company">日本精工</div>
<div class="company">住友ゴム</div>
<div class="company">日立製作所オートモティブ</div>
<div class="company">日本特殊陶業</div>
<div class="company">豊田合成</div>
<div class="company">NTN</div>
<div class="company">東海ゴム</div>
<div class="company">富士通テン</div>
<h3 class="rank5"> Dランク 偏差値50～54 </h3>
<div class="company">三菱ふそう</div>
<div class="company">日産ディーゼル</div>
<div class="company">東海理化</div>
<div class="company">小糸製作所</div>
<div class="company">ユタカ技研</div>
<div class="company">スタンレー電気</div>
<div class="company">横浜ゴム</div>
<div class="company">八千代工業</div>
<div class="company">アイシンAI</div>
<div class="company">カルソニックカンセイ ショーワ</div>
<div class="company">ケーヒン</div>
<div class="company">ジャトコ</div>
<div class="company">産車体</div>
<div class="company">日信工業</div>
<div class="company">デフテック</div>
<div class="company">カヤバ工業</div>
<div class="company">住友電装</div>
<div class="company">アルパイン</div>
<div class="company">NOK</div>
<div class="company">アイシン高丘</div>
<div class="company">矢崎総業</div>
<div class="company">トピー工業</div>
<div class="company">タカタ</div>
<div class="company">愛知製鋼</div>
<div class="company">シマノ</div>
<div class="company">アスモ</div>
<div class="company">ニッパツ</div>
<div class="company">フジオーゼックス</div>
<div class="company">東洋ゴム</div>
<div class="company">市光工業</div>
<div class="company">オーテックジャパン</div>
<div class="company">NISMO</div>
<div class="company">FCC</div>
<div class="company">サンデン</div>
<div class="company">英エステック</div>
<div class="company">豊生ブレーク</div>
<div class="company">中央発條</div>
<div class="company">シロキ興業</div>
<div class="company">愛三工業</div>
<div class="company">曙ブレーキ</div>
<div class="company">山田製作所</div>
<div class="company">光岡自動車</div>
<div class="company">愛知機械</div>
<div class="company">タチエス</div>
<div class="company">TRDb日鍛バルブ</div>
<div class="company">TGK</div>
<div class="company">日産工機</div>
<div class="company">大豊工業</div>
<div class="company">鬼怒川ゴム</div>
<div class="company">ブリヂストンサイクル</div>
<h3 class="rank6"> Eランク 偏差値45～49 </h3>
<div class="company">ボルグワーナモールステック</div>
<div class="company">TRWオートモーティブ</div>
<div class="company">武蔵精密</div>
<div class="company">プレス工業</div>
<div class="company">太平洋工業</div>
<div class="company">日本デルフォイオート</div>
<div class="company">村上開明堂</div>
<div class="company">共和レザー</div>
<div class="company">フジユニバンス</div>
<div class="company">河西興業</div>
<div class="company">富士機工</div>
<div class="company">エフテック</div>
<h3 class="rank7"> Fランク 偏差値40～44 </h3>
<div class="company">山下ゴム</div>
<div class="company">エンケイ</div>
<div class="company">アイエス精機</div>
<div class="company">豊和繊維工業</div>
<div class="company">飯田ネーム製作所</div>
<div class="company">フタバ産業</div>

</div>
</section><!-- /Case1 -->

